version: '3.4'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/confing/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/build:/var/www/html
