version: '3.4'

services:
  nginx:
    image: localhost:5000/lambdaloopers/nginx
    restart: always
    networks:
      - gateway
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - "traefik.docker.network=traefik_gateway"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:nginxexample.com"
        - "traefik.backend=nginx-client"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 1s
      retries: 5

configs:
  nginx_config:
    file: ./docker/nginx/config/default.conf

networks:
  gateway:
    external:
      name: traefik_gateway
